### PR TITLE
V2.6.1

### PR DESCRIPTION
**Pull request by samadhangudekar**
need new archive changes

### CODE REVIEW

**Comment by schedulix** [comment]
Hi,

the way we use git is that we have a master branch which always points to the most current code. Each time we reach a point where we want to create a stable release (like v2.6, v2.6.1, ...) we branch.
From there bug fixes are applied to the master branch as well as most stable branches.
Occasionally we also backport some important new features to the last stable branch, but there have to be very good reasons for this.
Backward compatibility is regarded extremely important (== a must be).

Having said this it should be obvious that forwarding changes shouldn't be necessary. It is theoretically possible that we fixed some single issue in a previous release and forgot to fix the same in the subsequent releases. We're only humans. But it is simply impossible to find 50 fixes that didn't reach the master branch.

What are you trying to achieve?

Regards,

Ronald

**Comment by samadhangudekar** [comment]
Hi Donald,


I was looking for changes DBCleanupThread.java as I was facing issue with archive (i.e. // statement for audit trail taken out). So I was about to make pull request. Then I found changes in DBCleanupThread.java of 2.6.1 and used that file.


Regards,
Samadhan Gudekar
+919833788253
________________________________

**Comment by schedulix** [comment]
Hi Samadhan,

this was a case where a fast fix for the stable releases (which turned out to be not as stable as we wanted) was necessary. In such cases we fix the customer's problem first, and update the unstable master branch afterwards. AFAIK it has been fixed there too in the meanwhile.

Is there any action I should take? If not, please close the issue (or tell me to do so).

Regards,

Ronald

**Comment by samadhangudekar** [comment]
Hi Ronald,


I pulled DBCleanupThread.java from 2.6.1 at GIT and recompiled BICsuite.jar.


I have closed it.


Regards,
Samadhan Gudekar
+919833788253
________________________________

**Pull request closed without merging**
